name: CI

on:
  push:
  workflow_dispatch:

jobs:
  deno:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Code Style
        run: deno fmt --check

      - name: Linting
        run: deno lint && deno doc --lint mod.ts

      - name: Type Check
        run: deno check ./scripts/*.ts ./*.ts

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - run: deno task build

  size:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - run: deno task gzip
